- .github/workflows/deploy.yaml
> ci: remove path filter

- AboutAxon
This is the About Axon section of the docs site.
> docs: add about axon introduction

- docs/about-axon/Why_Build_With_Axon.md
> docs: update Why_Build_With_Axon.md

- docs/for-dapp-devs/Zero_To_Axon_With_Axon_Cli.md
> docs: fix content bug

- docs/for-dapp-devs/Zero_To_Axon_With_Axon_Cli.md
update format of zero_to_axon
style: fix div format
fix div format
style: change div format
add blank line in div
style: fix div ci
fix div ci
style: fix div ci
fix ci of div
style: fix div
fix div of mk
style: fix ci error
fix ci error
style: remove color
remove color
> style: update tutorial format

- docs/for-dapp-devs/Zero_To_Axon_With_Axon_Cli.md
the previous one was not correct
> fix the link of axon-cli

- docs/for-dapp-devs/Zero_To_Axon_With_Axon_Cli.md
> fix: replace clone url

- docs/DevOps/_category_.json
create _category_.json for DevOps section
> docs: create DevOps _category_.json

- docs/for-dapp-devs/troubleshooting.md
add troubleshooting subsection under "For DApp Devs"
> docs: create troubleshooting.md

- docs/for-dapp-devs/deploy_dapps.md
> docs: create deploy_dapps.md

- docs/api/latest_version.md
> docs: create latest_version.md

- docs/getting-started/for-dapp-devs/zero_to_axon_with_axon_cli.md
> docs: update zero_to_axon_with_axon_cli.md

- wordlist.txt
Added new words from the latest essay Executor
> chore: update wordlist.txt

- docs/why_build_with_axon.mdx
> docs: update why_build_with_axon.mdx

- docs/devops/configuration.md
> fix: outdated link in configuration.md

- wordlist.txt
Add new items from Design Pattern
> docs: update wordlist.txt

- docs/getting-started/for-contributor/design_pattern.md
resize images in design pattern
> docs: update design_pattern.md

- docs/devops/explorer.md
- docs/devops/faucet.md
- docs/devops/proc-macros.md
- docs/devops/proxy.md
add a new article on proc-macros in devops section
> docs: add proc macros document

- docs/getting-started/for-dapp-devs/deploy_dapps.md
- docs/getting-started/for-dapp-devs/deploy_solidity.md
- docs/getting-started/for-dapp-devs/troubleshooting.md
create a new essay on solidity contract deployment
> docs: add deploy solidity contract doc

- docs/getting-started/for-dapp-devs/quick_start.md
> Fix the image link in `quick_start.md`

- docs/getting-started/for-dapp-devs/deploy_solidity.md
- docs/getting-started/for-dapp-devs/quick_start.md
- docs/getting-started/for-dapp-devs/send_transactions_on_axon_via_metaMask.md
- The default dev chain id is changed since https://github.com/axonweb3/axon/pull/1418.
> Update the chain ID of the Axon devnet

- AboutAxon
- docs/why_build_with_axon.mdx
replace Axon-CLI links with quick start
> Remove axon cli

- docs/contract/precompile_contracts.md
- docs/contract/system_contacts.md
> docs: fix precompile and system contract address

- docs/devops/configuration.md
- https://github.com/axonweb3/axon/pull/1531
> docs: update configuration.md

- docs/contract/system_contacts.md
Maintain consistency with [metadata_abi.json](https://github.com/axonweb3/axon/blob/main/core/executor/src/system_contract/metadata/abi/metadata_abi.json), [ckb_light_client_abi.json](https://github.com/axonweb3/axon/blob/main/core/executor/src/system_contract/ckb_light_client/abi/ckb_light_client_abi.json), and [image_cell_abi.json](https://github.com/axonweb3/axon/blob/main/core/executor/src/system_contract/image_cell/abi/image_cell_abi.json).
> docs: update the ABI of system_contacts
